In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
namyangju_2210 = pd.read_csv("/content/drive/MyDrive/DSL/EDA/2210_남양주_1700,2000,7007.xls.csv", encoding = 'cp949')
namyangju_2211 = pd.read_csv("/content/drive/MyDrive/DSL/EDA/2211_남양주_1700,2000,7007_수정본.xls.csv")

In [4]:
namyangju_2210.head()

,년도,월,지역,노선,시?종점 (출발?도착지점),일시,시간,승차,하차,전체,승차.1,하차.1,전체.1,승차.2,하차.2,전체.2
0,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,05시~06시,52,25,77,8,1,9,60,26,86
1,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,06시~07시,120,50,170,13,11,24,133,61,194
2,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,07시~08시,105,84,189,26,24,50,131,108,239
3,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,08시~09시,73,118,191,86,89,175,159,207,366
4,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,09시~10시,35,67,102,36,33,69,71,100,171

In [5]:
namyangju_2211.head()

,년도,월,지역,노선,시•종점 (출발•도착지점),일시,시간,승차,하차,전체,승차.1,하차.1,전체.1,승차.2,하차.2,전체.2
0,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,05시~06시,43,21,64,6,1,7,49,22,71
1,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,06시~07시,100,38,138,25,14,39,125,52,177
2,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,07시~08시,126,76,202,34,35,69,160,111,271
3,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,08시~09시,94,126,220,55,51,106,149,177,326
4,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,09시~10시,44,103,147,38,48,86,82,151,233

# **남양주_출근시간대**

**10월**

In [6]:
con_1 = namyangju_2210['시간'] == '05시~06시'
con_2 = namyangju_2210['시간'] == '06시~07시'
con_3 = namyangju_2210['시간'] == '07시~08시'

In [8]:
am_namyangju_2210 = namyangju_2210.loc[con_1 | con_2 | con_3 ,  ]
am_namyangju_2210

,년도,월,지역,노선,시?종점 (출발?도착지점),일시,시간,승차,하차,전체,승차.1,하차.1,전체.1,승차.2,하차.2,전체.2
0,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,05시~06시,52,25,77,8,1,9,60,26,86
1,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,06시~07시,120,50,170,13,11,24,133,61,194
2,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,07시~08시,105,84,189,26,24,50,131,108,239
21,2022,10,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,05시~06시,83,1,84,3,0,3,86,1,87
22,2022,10,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,06시~07시,135,97,232,3,5,8,138,102,240
23,2022,10,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,07시~08시,160,67,227,33,9,42,193,76,269
42,2022,10,남양주시,7007,광릉내-강남역.강남역사거리,평일,05시~06시,74,1,75,1,0,1,75,1,76
43,2022,10,남양주시,7007,광릉내-강남역.강남역사거리,평일,06시~07시,162,55,217,13,1,14,175,56,231
44,2022,10,남양주시,7007,광릉내-강남역.강남역사거리,평일,07시~08시,137,97,234,39,37,76,176,134,310

**11월**

In [10]:
con_4 = namyangju_2211['시간'] == '05시~06시'
con_5 = namyangju_2211['시간'] == '06시~07시'
con_6 = namyangju_2211['시간'] == '07시~08시'

In [12]:
am_namyangju_2211 = namyangju_2211.loc[con_4 | con_5 | con_6 ,  ]
am_namyangju_2211

,년도,월,지역,노선,시•종점 (출발•도착지점),일시,시간,승차,하차,전체,승차.1,하차.1,전체.1,승차.2,하차.2,전체.2
0,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,05시~06시,43,21,64,6,1,7,49,22,71
1,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,06시~07시,100,38,138,25,14,39,125,52,177
2,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,07시~08시,126,76,202,34,35,69,160,111,271
22,2022,11,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,05시~06시,90,2,92,2,0,2,92,2,94
23,2022,11,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,06시~07시,130,85,215,4,3,7,134,88,222
24,2022,11,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,07시~08시,127,102,229,29,23,52,156,125,281
43,2022,11,남양주시,7007,광릉내-강남역.강남역사거리,평일,05시~06시,76,17,93,2,1,3,78,18,96
44,2022,11,남양주시,7007,광릉내-강남역.강남역사거리,평일,06시~07시,158,39,197,9,0,9,167,39,206
45,2022,11,남양주시,7007,광릉내-강남역.강남역사거리,평일,07시~08시,143,90,233,52,36,88,195,126,321

**10월, 11월 groupby**

In [13]:
am_namyangju_2210_df = am_namyangju_2210.loc[:, ['년도', '월', '지역', '노선', '시간', '승차.2']]
am_namyangju_2211_df = am_namyangju_2211.loc[:, ['년도', '월', '지역', '노선', '시간', '승차.2']]

In [26]:
am_namyangju_2210_df

      년도   월    지역    노선       시간  승차.2
0   2022  10  남양주시  1700  05시~06시    60
1   2022  10  남양주시  1700  06시~07시   133
2   2022  10  남양주시  1700  07시~08시   131
21  2022  10  남양주시  2000  05시~06시    86
22  2022  10  남양주시  2000  06시~07시   138
23  2022  10  남양주시  2000  07시~08시   193
42  2022  10  남양주시  7007  05시~06시    75
43  2022  10  남양주시  7007  06시~07시   175
44  2022  10  남양주시  7007  07시~08시   176

In [14]:
am_namyangju = pd.merge(am_namyangju_2210_df, am_namyangju_2211_df, how = 'left', on = '노선')
am_namyangju

    년도_x  월_x  지역_x    노선     시간_x  승차.2_x  년도_y  월_y  지역_y     시간_y  승차.2_y
0   2022   10  남양주시  1700  05시~06시      60  2022   11  남양주시  05시~06시      49
1   2022   10  남양주시  1700  05시~06시      60  2022   11  남양주시  06시~07시     125
2   2022   10  남양주시  1700  05시~06시      60  2022   11  남양주시  07시~08시     160
3   2022   10  남양주시  1700  06시~07시     133  2022   11  남양주시  05시~06시      49
4   2022   10  남양주시  1700  06시~07시     133  2022   11  남양주시  06시~07시     125
5   2022   10  남양주시  1700  06시~07시     133  2022   11  남양주시  07시~08시     160
6   2022   10  남양주시  1700  07시~08시     131  2022   11  남양주시  05시~06시      49
7   2022   10  남양주시  1700  07시~08시     131  2022   11  남양주시  06시~07시     125
8   2022   10  남양주시  1700  07시~08시     131  2022   11  남양주시  07시~08시     160
9   2022   10  남양주시  2000  05시~06시      86  2022   11  남양주시  05시~06시      92
10  2022   10  남양주시  2000  05시~06시      86  2022   11  남양주시  06시~07시     134
11  2022   10  남양주시  2000  05시~06시      86  2022   11  남양주시  07시~08시     156
12  2022   10  남양주시  2000  06시~07시     138  2022   11  남양주시  05시~06시      92
13  2022   10  남양주시  2000  06시~07시     138  2022   11  남양주시  06시~07시     134
14  2022   10  남양주시  2000  06시~07시     138  2022   11  남양주시  07시~08시     156
15  2022   10  남양주시  2000  07시~08시     193  2022   11  남양주시  05시~06시      92
16  2022   10  남양주시  2000  07시~08시     193  2022   11  남양주시  06시~07시     134
17  2022   10  남양주시  2000  07시~08시     193  2022   11  남양주시  07시~08시     156
18  2022   10  남양주시  7007  05시~06시      75  2022   11  남양주시  05시~06시      78
19  2022   10  남양주시  7007  05시~06시      75  2022   11  남양주시  06시~07시     167
20  2022   10  남양주시  7007  05시~06시      75  2022   11  남양주시  07시~08시     195
21  2022   10  남양주시  7007  06시~07시     175  2022   11  남양주시  05시~06시      78
22  2022   10  남양주시  7007  06시~07시     175  2022   11  남양주시  06시~07시     167
23  2022   10  남양주시  7007  06시~07시     175  2022   11  남양주시  07시~08시     195
24  2022   10  남양주시  7007  07시~08시     176  2022   11  남양주시  05시~06시      78
25  2022   10  남양주시  7007  07시~08시     176  2022   11  남양주시  06시~07시     167
26  2022   10  남양주시  7007  07시~08시     176  2022   11  남양주시  07시~08시     195

In [15]:
am_namyangju_group = am_namyangju.groupby(['시간_x', '노선'])
am_namyangju_group.mean()

                년도_x   월_x  승차.2_x    년도_y   월_y      승차.2_y
시간_x    노선
05시~06시 1700  2022.0  10.0    60.0  2022.0  11.0  111.333333
        2000  2022.0  10.0    86.0  2022.0  11.0  127.333333
        7007  2022.0  10.0    75.0  2022.0  11.0  146.666667
06시~07시 1700  2022.0  10.0   133.0  2022.0  11.0  111.333333
        2000  2022.0  10.0   138.0  2022.0  11.0  127.333333
        7007  2022.0  10.0   175.0  2022.0  11.0  146.666667
07시~08시 1700  2022.0  10.0   131.0  2022.0  11.0  111.333333
        2000  2022.0  10.0   193.0  2022.0  11.0  127.333333
        7007  2022.0  10.0   176.0  2022.0  11.0  146.666667

**ANOVA assumption**

In [33]:
import statsmodels.api as sm
from scipy import stats
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

In [34]:
am_namyangju_2210_df

      년도   월    지역    노선       시간  승차.2
0   2022  10  남양주시  1700  05시~06시    60
1   2022  10  남양주시  1700  06시~07시   133
2   2022  10  남양주시  1700  07시~08시   131
21  2022  10  남양주시  2000  05시~06시    86
22  2022  10  남양주시  2000  06시~07시   138
23  2022  10  남양주시  2000  07시~08시   193
42  2022  10  남양주시  7007  05시~06시    75
43  2022  10  남양주시  7007  06시~07시   175
44  2022  10  남양주시  7007  07시~08시   176

In [35]:
am_namyangju_2211_df

      년도   월    지역    노선       시간  승차.2
0   2022  11  남양주시  1700  05시~06시    49
1   2022  11  남양주시  1700  06시~07시   125
2   2022  11  남양주시  1700  07시~08시   160
22  2022  11  남양주시  2000  05시~06시    92
23  2022  11  남양주시  2000  06시~07시   134
24  2022  11  남양주시  2000  07시~08시   156
43  2022  11  남양주시  7007  05시~06시    78
44  2022  11  남양주시  7007  06시~07시   167
45  2022  11  남양주시  7007  07시~08시   195

In [38]:
F, p = stats.f_oneway(am_namyangju_2210_df, am_namyangju_2211_df)
print( 'F-Ratio: {}'.format(F)
    , 'p-value:{}'.format(p)
     , sep = '\n')

ValueError: ignored

# **남양주_퇴근시간대**

**10월**

In [16]:
con_a = namyangju_2210['시간'] == '17시~18시'
con_b = namyangju_2210['시간'] == '18시~19시'
con_c = namyangju_2210['시간'] == '19시~20시'

In [17]:
pm_namyangju_2210 = namyangju_2210.loc[con_a | con_b | con_c ,  ]
pm_namyangju_2210

,년도,월,지역,노선,시?종점 (출발?도착지점),일시,시간,승차,하차,전체,승차.1,하차.1,전체.1,승차.2,하차.2,전체.2
12,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,17시~18시,66,60,126,44,39,83,110,99,209
13,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,18시~19시,68,50,118,28,17,45,96,67,163
14,2022,10,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,19시~20시,59,80,139,55,68,123,114,148,262
33,2022,10,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,17시~18시,177,182,359,54,52,106,231,234,465
34,2022,10,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,18시~19시,185,101,286,67,36,103,252,137,389
35,2022,10,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,19시~20시,118,158,276,58,72,130,176,230,406
54,2022,10,남양주시,7007,광릉내-강남역.강남역사거리,평일,17시~18시,85,57,142,41,45,86,126,102,228
55,2022,10,남양주시,7007,광릉내-강남역.강남역사거리,평일,18시~19시,98,75,173,53,30,83,151,105,256
56,2022,10,남양주시,7007,광릉내-강남역.강남역사거리,평일,19시~20시,79,94,173,44,42,86,123,136,259

**11월**

In [18]:
con_d = namyangju_2211['시간'] == '17시~18시'
con_e = namyangju_2211['시간'] == '18시~19시'
con_f = namyangju_2211['시간'] == '19시~20시'

In [19]:
pm_namyangju_2211 = namyangju_2211.loc[con_d | con_e | con_f ,  ]
pm_namyangju_2211

,년도,월,지역,노선,시•종점 (출발•도착지점),일시,시간,승차,하차,전체,승차.1,하차.1,전체.1,승차.2,하차.2,전체.2
12,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,17시~18시,63,60,123,31,34,65,94,94,188
13,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,18시~19시,73,43,116,52,19,71,125,62,187
14,2022,11,남양주시,1700,연대농장입구.도곡리종점-신논현역.우신빌딩,평일,19시~20시,68,81,149,50,60,110,118,141,259
34,2022,11,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,17시~18시,149,112,261,58,37,95,207,149,356
35,2022,11,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,18시~19시,169,142,311,65,53,118,234,195,429
36,2022,11,남양주시,2000,진벌리차고지(경유)-강남역.강남역사거리,평일,19시~20시,86,122,208,63,51,114,149,173,322
55,2022,11,남양주시,7007,광릉내-강남역.강남역사거리,평일,17시~18시,79,47,126,39,19,58,118,66,184
56,2022,11,남양주시,7007,광릉내-강남역.강남역사거리,평일,18시~19시,88,75,163,61,47,108,149,122,271
57,2022,11,남양주시,7007,광릉내-강남역.강남역사거리,평일,19시~20시,59,92,151,59,53,112,118,145,263

**10월, 11월 groupby**

In [21]:
pm_namyangju_2210_df = pm_namyangju_2210.loc[:, ['년도', '월', '지역', '노선', '시간', '승차.2']]
pm_namyangju_2211_df = pm_namyangju_2211.loc[:, ['년도', '월', '지역', '노선', '시간', '승차.2']]

In [22]:
pm_namyangju = pd.merge(pm_namyangju_2210_df, pm_namyangju_2211_df, how = 'left', on = '노선')
pm_namyangju

    년도_x  월_x  지역_x    노선     시간_x  승차.2_x  년도_y  월_y  지역_y     시간_y  승차.2_y
0   2022   10  남양주시  1700  17시~18시     110  2022   11  남양주시  17시~18시      94
1   2022   10  남양주시  1700  17시~18시     110  2022   11  남양주시  18시~19시     125
2   2022   10  남양주시  1700  17시~18시     110  2022   11  남양주시  19시~20시     118
3   2022   10  남양주시  1700  18시~19시      96  2022   11  남양주시  17시~18시      94
4   2022   10  남양주시  1700  18시~19시      96  2022   11  남양주시  18시~19시     125
5   2022   10  남양주시  1700  18시~19시      96  2022   11  남양주시  19시~20시     118
6   2022   10  남양주시  1700  19시~20시     114  2022   11  남양주시  17시~18시      94
7   2022   10  남양주시  1700  19시~20시     114  2022   11  남양주시  18시~19시     125
8   2022   10  남양주시  1700  19시~20시     114  2022   11  남양주시  19시~20시     118
9   2022   10  남양주시  2000  17시~18시     231  2022   11  남양주시  17시~18시     207
10  2022   10  남양주시  2000  17시~18시     231  2022   11  남양주시  18시~19시     234
11  2022   10  남양주시  2000  17시~18시     231  2022   11  남양주시  19시~20시     149
12  2022   10  남양주시  2000  18시~19시     252  2022   11  남양주시  17시~18시     207
13  2022   10  남양주시  2000  18시~19시     252  2022   11  남양주시  18시~19시     234
14  2022   10  남양주시  2000  18시~19시     252  2022   11  남양주시  19시~20시     149
15  2022   10  남양주시  2000  19시~20시     176  2022   11  남양주시  17시~18시     207
16  2022   10  남양주시  2000  19시~20시     176  2022   11  남양주시  18시~19시     234
17  2022   10  남양주시  2000  19시~20시     176  2022   11  남양주시  19시~20시     149
18  2022   10  남양주시  7007  17시~18시     126  2022   11  남양주시  17시~18시     118
19  2022   10  남양주시  7007  17시~18시     126  2022   11  남양주시  18시~19시     149
20  2022   10  남양주시  7007  17시~18시     126  2022   11  남양주시  19시~20시     118
21  2022   10  남양주시  7007  18시~19시     151  2022   11  남양주시  17시~18시     118
22  2022   10  남양주시  7007  18시~19시     151  2022   11  남양주시  18시~19시     149
23  2022   10  남양주시  7007  18시~19시     151  2022   11  남양주시  19시~20시     118
24  2022   10  남양주시  7007  19시~20시     123  2022   11  남양주시  17시~18시     118
25  2022   10  남양주시  7007  19시~20시     123  2022   11  남양주시  18시~19시     149
26  2022   10  남양주시  7007  19시~20시     123  2022   11  남양주시  19시~20시     118

In [23]:
pm_namyangju_group = pm_namyangju.groupby(['시간_x', '노선'])
pm_namyangju_group.mean()

                년도_x   월_x  승차.2_x    년도_y   월_y      승차.2_y
시간_x    노선
17시~18시 1700  2022.0  10.0   110.0  2022.0  11.0  112.333333
        2000  2022.0  10.0   231.0  2022.0  11.0  196.666667
        7007  2022.0  10.0   126.0  2022.0  11.0  128.333333
18시~19시 1700  2022.0  10.0    96.0  2022.0  11.0  112.333333
        2000  2022.0  10.0   252.0  2022.0  11.0  196.666667
        7007  2022.0  10.0   151.0  2022.0  11.0  128.333333
19시~20시 1700  2022.0  10.0   114.0  2022.0  11.0  112.333333
        2000  2022.0  10.0   176.0  2022.0  11.0  196.666667
        7007  2022.0  10.0   123.0  2022.0  11.0  128.333333