In [63]:
import os
import pandas as pd
import numpy as np
#경로 -> 상대경로 사용
PATH = '버스노선별_승하차_인원/'
#모든 파일 이름을 리스트로 가져옴
file_list, csv_list = os.listdir(PATH), list()
for file in file_list:
    if file.split('.')[-1] == 'csv':
        csv_list.append(file)
#boolean flag를 활용해 첫 데이터프레임을 생성, 이후엔 기존 데이터프레임과 새 데이터프레임 병합 방법 사용
boolean_flag_1 = True
boolean_flag_2 = True
for csv_file in csv_list:
#각각의 데이터 저장 시 인코딩 방식 혼용함 -> try, except 구문 활용하여 인코딩 방식이 다른 문제 해결
    try:
        df_whole = pd.read_csv(PATH + csv_file, encoding = 'cp949')
    except:
        df_whole = pd.read_csv(PATH + csv_file, encoding = 'utf-8-sig')
#표준 컬럼 리스트 설정
    if boolean_flag_1:
        standard_column_list = list(df_whole.columns)
        boolean_flag_1 = False
#컬럼명, 컬럼 길이가 다른 부분 존재 -> 기존 컬럼 리스트를 복사해서 가져와 길이에 맞게 버스 코드 컬럼 인자를 삽입.
    print(standard_column_list)
    if list(df_whole.columns) != standard_column_list:
        try:
            print(1)
            df_whole = df_whole[standard_column_list]
        except:
            std_column_list_copy = standard_column_list.copy()
            std_column_list_copy.insert(1,'bus_code')
        
            df_whole.columns = std_column_list_copy
    else:
        pass
    df_whole = df_whole.groupby('노선번호').sum()[['승차총승객수','하차총승객수']]
#문자열 포맷팅을 이용해 연도, 월별 컬럼명 기입 자동화함
    df_whole['승하차_평균_{}'.format(csv_file.split('.')[-2][-4:])] = (df_whole['승차총승객수'] + df_whole['하차총승객수']) / 2
    df_whole = df_whole[['승하차_평균_{}'.format(csv_file.split('.')[-2][-4:])]].astype('int')
    df_whole = df_whole.reset_index()
    print(df_whole)
    if boolean_flag_2:
        df_bus = df_whole
        boolean_flag_2 = False
    else:
        df_bus = pd.merge(df_bus, df_whole, on = '노선번호', how = 'outer')
list_name = list(df_bus['노선번호'])
list_bus =list()
#중복된 노선이지만 데이터 타입이 다른경우 -> try except 구문 이용하여 데이터 타입 변경
for name in list_name:
    if type(name) == str:
        name = name.split('(')[0].lstrip('0')
        try:
            name = int(name)
        except:
            pass

    list_bus.append(name)
df_bus['노선번호'] = list_bus
df_bus = df_bus.groupby('노선번호').sum().astype('int')
df_bus

['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1501
0    0017       193298
1      02        89065
2      03        40176
3      05        50488
4     100       522986
..    ...          ...
597  종로11       104105
598  종로12        81691
599  종로13        32757
600  중랑01        17239
601  중랑02       199103

[602 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1502
0    0017       165367
1      02        81164
2      03        33309
3      05        48445
4     100       448227
..    ...          ...
600  종로11        91142
601  종로12        67073
602  종로13        29184
603  중랑01        15302
604  중랑02       174694

[605 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1503
0    0017       202828
1      02        91316
2      03        35269
3      05        45704
4     100       584219
..    ...          ...
594  종로11       105571
595  종로12        83137
596  종로13        58565
597  중랑01        18798
598  중랑02       254811

[599 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1504
0    0017       200612
1      02       125745
2      03        44765
3      05        57310
4     100       583498
..    ...          ...
594  종로11       107068
595  종로12        81627
596  종로13        58687
597  중랑01        18460
598  중랑02       244027

[599 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1505
0    0017       198500
1      02       135108
2      03        49275
3      05        60338
4     100       587213
..    ...          ...
595  종로11       114475
596  종로12        74401
597  종로13        57586
598  중랑01        18248
599  중랑02       230591

[600 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1506
0    0017       187989
1      02        73445
2      03        26210
3      05        31233
4     100       532019
..    ...          ...
595  종로11        90830
596  종로12        61782
597  종로13        55115
598  중랑01        17177
599  중랑02       211303

[600 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1507
0    0017       204017
1      02        73054
2      03        30762
3      05        36686
4     100       554123
..    ...          ...
596  종로11       105741
597  종로12        79382
598  종로13        43325
599  중랑01        17108
600  중랑02       193553

[601 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1508
0    0017       195880
1      02        85973
2      03        46422
3      05        59144
4     100       535262
..    ...          ...
599  종로11       111103
600  종로12        79812
601  종로13        40204
602  중랑01        16123
603  중랑02       188940

[604 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1509
0    0017       195203
1      02        81681
2      03        44784
3      05        66140
4     100       552178
..    ...          ...
596  종로11       101171
597  종로12        74815
598  종로13        57340
599  중랑01        16923
600  중랑02       212767

[601 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1510
0    0017       201271
1      02        84729
2      03        42152
3      05        69513
4     100       587617
..    ...          ...
596  종로11       105088
597  종로12        76601
598  종로13        59359
599  중랑01        17350
600  중랑02       225801

[601 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1511
0    0017       188571
1      02        56862
2      03        34733
3      05        62018
4     100       540985
..    ...          ...
597  종로11        96139
598  종로12        77018
599  종로13        56371
600  중랑01        16484
601  중랑02       213680

[602 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1512
0    0017       197519
1      02        72605
2      03        35270
3      05        61755
4     100       559529
..    ...          ...
598  종로11       103081
599  종로12        81373
600  종로13        49336
601  중랑01        17679
602  중랑02       210195

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1601
0    0017       175088
1      02        70695
2      03        32107
3      05        56124
4     100       490848
..    ...          ...
597  종로11        98532
598  종로12        76058
599  종로13        31867
600  중랑01        16260
601  중랑02       179227

[602 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1602
0    0017       165775
1      02        72703
2      03        29344
3      05        50981
4     100       457383
..    ...          ...
598  종로11        90522
599  종로12        70007
600  종로13        30129
601  중랑01        15368
602  중랑02       168917

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1603
0    0017       193656
1      02        83408
2      03        33367
3      05        54744
4     100       579581
..    ...          ...
600  종로11        98269
601  종로12        83320
602  종로13        56398
603  중랑01        18243
604  중랑02       233368

[605 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1604
0    0017       184733
1      02       117574
2      03        52080
3      05        72503
4     100       560291
..    ...          ...
600  종로11        99029
601  종로12        78669
602  종로13        53357
603  중랑01        17297
604  중랑02       218093

[605 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1605
0    0017       192352
1      02       103785
2      03        48788
3      05        63262
4     100       566981
..    ...          ...
598  종로11       104501
599  종로12        81405
600  종로13        56888
601  중랑01        17704
602  중랑02       219412

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1606
0    0017       188264
1      02        80235
2      03        45888
3      05        59467
4     100       554973
..    ...          ...
598  종로11        98864
599  종로12        81527
600  종로13        54321
601  중랑01        17282
602  중랑02       205768

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1607
0    0017       197019
1      02        59931
2      03        41268
3      05        66376
4     100       541407
..    ...          ...
600  종로11       100256
601  종로12        85541
602  종로13        40246
603  중랑01        17320
604  중랑02       186569

[605 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1608
0    0017       197742
1      02        65417
2      03        44174
3      05        70065
4     100       533866
..    ...          ...
599  종로11       104797
600  종로12        88396
601  종로13        41092
602  중랑01        17286
603  중랑02       193314

[604 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1609
0    0017       185071
1      02        75016
2      03        46386
3      05        71114
4     100       531007
..    ...          ...
600  종로11        96818
601  종로12        80641
602  종로13        54000
603  중랑01        16470
604  중랑02       204097

[605 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1610
0    0017       195149
1      02        78672
2      03        47127
3      05        82030
4     100       571556
..    ...          ...
598  종로11       103702
599  종로12        81402
600  종로13        56076
601  중랑01        17036
602  중랑02       212862

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1611
0    0017       192363
1      02        63923
2      03        39797
3      05        57647
4     100       556140
..    ...          ...
598  종로11        82060
599  종로12        80563
600  종로13        57159
601  중랑01        16838
602  중랑02       214238

[603 rows x 2 columns]

['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1612
0    0017       195498
1      02        61455
2      03        41477
3      05        55876
4     100       551405
..    ...          ...
598  종로11        80469
599  종로12        84299
600  종로13        49582
601  중랑01        16943
602  중랑02       206685

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1701
0    0017       175314
1      02        59811
2      03        38875
3      05        51476
4     100       471015
..    ...          ...
598  종로11        79450
599  종로12        75907
600  종로13        29560
601  중랑01        14947
602  중랑02       171111

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1702
0    0017       171171
1      02        51496
2      03        37365
3      05        49738
4     100       476073
..    ...          ...
599  종로11        77615
600  종로12        70537
601  종로13        30724
602  중랑01        14422
603  중랑02       167615

[604 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1703
0    0017       193494
1      02        57428
2      03        39602
3      05        55480
4     100       565992
..    ...          ...
600  종로11        84097
601  종로12        74968
602  종로13        53435
603  중랑01        16596
604  중랑02       226162

[605 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1704
0    0017       182188
1      02        85587
2      03        58226
3      05        79955
4     100       551145
..    ...          ...
598  종로11        96769
599  종로12        71006
600  종로13        51512
601  중랑01        15562
602  중랑02       215482

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1705
0    0017       184894
1      02        71685
2      03        50123
3      05        64452
4     100       559475
..    ...          ...
598  종로11       104545
599  종로12        69702
600  종로13        53695
601  중랑01        16536
602  중랑02       212523

[603 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1706
0    0017       187202
1      02        55216
2      03        42117
3      05        53551
4     100       545051
..    ...          ...
603  종로11        99515
604  종로12        70271
605  종로13        50790
606  중랑01        16370
607  중랑02       203599

[608 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1707
0    0017       189174
1      02        47171
2      03        36927
3      05        45603
4     100       527009
..    ...          ...
603  종로11        99173
604  종로12        74580
605  종로13        38049
606  중랑01        16378
607  중랑02       185008

[608 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1708
0    0017       168835
1      02        54359
2      03        45889
3      05        52504
4     100       525790
..    ...          ...
605  종로11        91279
606  종로12        64598
607  종로13        32589
608  중랑01        13940
609  중랑02       163385

[610 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1709
0    0017       195786
1      02        64879
2      03        47263
3      05        59790
4     100       561429
..    ...          ...
605  종로11       103743
606  종로12        71838
607  종로13        55117
608  중랑01        17106
609  중랑02       214367

[610 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1710
0    0017       171429
1      02        99332
2      03        61768
3      05        81401
4     100       503385
..    ...          ...
607  종로11        99468
608  종로12        59864
609  종로13        46174
610  중랑01        15340
611  중랑02       192395

[612 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1711
0    0017       186945
1      02        61771
2      03        38831
3      05        54703
4     100       531320
..    ...          ...
604  종로11        97615
605  종로12        74676
606  종로13        52623
607  중랑01        16772
608  중랑02       212721

[609 rows x 2 columns]

C:\Users\swnam\AppData\Local\Temp\ipykernel_21068\1300018004.py:17: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_whole = pd.read_csv(PATH + csv_file, encoding = 'cp949')

['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1712
0    1124          384
1    1126         7435
2    1128         4888
3    1129          796
4    1130         2345
..    ...          ...
679  종로11        97886
680  종로12        69263
681  종로13        45835
682  중랑01        16546
683  중랑02       204019

[684 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1801
0    0017       177470
1      02        58509
2      03        33298
3      05        38313
4     100       475796
..    ...          ...
604  종로11        89571
605  종로12        75265
606  종로13        29832
607  중랑01        16425
608  중랑02       182690

[609 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1802
0    0017       158965
1      02        56941
2      03        33531
3      05        38336
4     100       418059
..    ...          ...
602  종로11        81789
603  종로12        62938
604  종로13        26012
605  중랑01        14275
606  중랑02       162727

[607 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1803
0    0017       188546
1      02        74739
2      03        41719
3      05        50706
4     100       535214
..    ...          ...
608  종로11        96792
609  종로12        74701
610  종로13        50026
611  중랑01        17135
612  중랑02       227605

[613 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1804
0    0017       181503
1      02        96773
2      03        51695
3      05        66875
4     100       522478
..    ...          ...
606  종로11        97572
607  종로12        72268
608  종로13        50477
609  중랑01        16315
610  중랑02       219844

[611 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1805
0    0017       177882
1      02        95590
2      03        51224
3      05        61162
4     100       528239
..    ...          ...
606  종로11        99290
607  종로12        71746
608  종로13        48004
609  중랑01        15769
610  중랑02       209685

[611 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1806
0    0017       165370
1      02        79150
2      03        43598
3      05        50225
4     100       474396
..    ...          ...
606  종로11        89481
607  종로12        63453
608  종로13        43301
609  중랑01        14681
610  중랑02       183840

[611 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1807
0    0017       195209
1      02        70603
2      03        39093
3      05        43700
4     100       504203
..    ...          ...
606  종로11        94410
607  종로12        79565
608  종로13        36451
609  중랑01        16720
610  중랑02       184717

[611 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1808
0    0017       198211
1      02        79713
2      03        42757
3      05        48141
4     100       510599
..    ...          ...
609  종로11       101789
610  종로12        80540
611  종로13        35094
612  중랑01        16027
613  중랑02       195843

[614 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1809
0    0017       176886
1      02       108575
2      03        57334
3      05        66446
4     100       500772
..    ...          ...
606  종로11        95490
607  종로12        65776
608  종로13        46497
609  중랑01        15515
610  중랑02       196119

[611 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1810
0    0017       194078
1      02       109071
2      03        52990
3      05        69553
4     100       555575
..    ...          ...
608  종로11       100265
609  종로12        70938
610  종로13        53345
611  중랑01        17108
612  중랑02       219915

[613 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1811
0    0017       193532
1      02        87448
2      03        45867
3      05        57127
4     100       545683
..    ...          ...
612  종로11        98163
613  종로12        74223
614  종로13        52716
615  중랑01        16337
616  중랑02       213934

[617 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1812
0    0017       187481
1      02        80077
2      03        42350
3      05        52508
4     100       532547
..    ...          ...
612  종로11        94108
613  종로12        71106
614  종로13        44342
615  중랑01        14990
616  중랑02       196525

[617 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1901
0    0017       178849
1      02        70095
2      03        37314
3      05        47385
4     100       505027
..    ...          ...
608  종로11        92994
609  종로12        75564
610  종로13        30794
611  중랑01        14750
612  중랑02       181133

[613 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1902
0    0017       156743
1      02        66732
2      03        37028
3      05        49099
4     100       435106
..    ...          ...
608  종로11        80921
609  종로12        62386
610  종로13        25659
611  중랑01        12629
612  중랑02       155709

[613 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1903
0    0017       184504
1      02        83886
2      03        43757
3      05        58439
4     100       555219
..    ...          ...
609  종로11        96037
610  종로12        72623
611  종로13        51887
612  중랑01        15122
613  중랑02       217420

[614 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1904
0    0017       183426
1      02       108006
2      03        55839
3      05        77054
4     100       566246
..    ...          ...
609  종로11        97993
610  종로12        75891
611  종로13        54154
612  중랑01        14868
613  중랑02       218160

[614 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1905
0    0017       188978
1      02        93757
2      03        50074
3      05        65917
4     100       590442
..    ...          ...
609  종로11       105618
610  종로12        75398
611  종로13        55294
612  중랑01        14938
613  중랑02       219409

[614 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1906
0    0017       178765
1      02        88478
2      03        48195
3      05        63857
4     100       535835
..    ...          ...
611  종로11        97255
612  종로12        70704
613  종로13        45857
614  중랑01        13979
615  중랑02       194484

[616 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1907
0    0017       193449
1      02        84023
2      03        44166
3      05        57337
4     100       550362
..    ...          ...
610  종로11       105402
611  종로12        83138
612  종로13        36576
613  중랑01        14705
614  중랑02       187243

[615 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1908
0    0017       186980
1      02        89573
2      03        48566
3      05        61705
4     100       531224
..    ...          ...
610  종로11       109651
611  종로12        80236
612  종로13        34276
613  중랑01        13370
614  중랑02       190601

[615 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1909
0    0017       177467
1      02        90133
2      03        46790
3      05        61372
4     100       518556
..    ...          ...
610  종로11        97467
611  종로12        70675
612  종로13        49701
613  중랑01        13396
614  중랑02       199522

[615 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1910
0    0017       188728
1      02       119655
2      03        57497
3      05        81397
4     100       581190
..    ...          ...
611  종로11       102518
612  종로12        74789
613  종로13        54224
614  중랑01        14040
615  중랑02       214457

[616 rows x 2 columns]

['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1911
0    0017       183585
1      02        93862
2      03        48719
3      05        62740
4     100       558461
..    ...          ...
612  종로11       100675
613  종로12        74244
614  종로13        51740
615  중랑01        12702
616  중랑02       205579

[617 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_1912
0    0017       186727
1      02        79733
2      03        43322
3      05        55779
4     100       559074
..    ...          ...
612  종로11       100882
613  종로12        75689
614  종로13        44127
615  중랑01        12542
616  중랑02       193695

[617 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2001
0    0017       164913
1     01A          552
2     01B          617
3      02        79847
4      03        36139
..    ...          ...
616  종로11        88146
617  종로12        70273
618  종로13        26198
619  중랑01        11446
620  중랑02       165878

[621 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2002
0    0017       141271
1     01A         8758
2     01B         9923
3      02        52586
4      03         2394
..    ...          ...
614  종로11        65287
615  종로12        60123
616  종로13        21173
617  중랑01         9875
618  중랑02       143474

[619 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2003
0    0017       119245
1     01A        11672
2     01B        11354
3      02        48711
4      03         1683
..    ...          ...
617  종로11        49020
618  종로12        51004
619  종로13        17274
620  중랑01         9154
621  중랑02       125052

[622 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2004
0    0017       121155
1     01A        15631
2     01B        14231
3      02        70743
4      03         1988
..    ...          ...
616  종로11        55805
617  종로12        53616
618  종로13        19655
619  중랑01         9830
620  중랑02       128969

[621 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2005
0    0017       136256
1     01A        18102
2     01B        16844
3      02        64023
4      03         3047
..    ...          ...
616  종로11        70697
617  종로12        56646
618  종로13        22385
619  중랑01        10821
620  중랑02       137612

[621 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2006
0    0017       151032
1     01A        20001
2     01B        19156
3      02        51955
4      03         3537
..    ...          ...
619  종로11        68154
620  종로12        63370
621  종로13        26872
622  중랑01        11064
623  중랑02       150366

[624 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2007
0    0017       162741
1     01A        22376
2     01B        21689
3      02        59533
4      03         4697
..    ...          ...
619  종로11        77227
620  종로12        68991
621  종로13        26564
622  중랑01        11880
623  중랑02       153616

[624 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2008
0    0017       142178
1     01A        18586
2     01B        18110
3      02        44719
4      03         3764
..    ...          ...
618  종로11        61775
619  종로12        59917
620  종로13        20519
621  중랑01        10319
622  중랑02       135562

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2009
0    0017       134465
1     01A        15375
2     01B        15000
3      02        56640
4      03         2794
..    ...          ...
618  종로11        58480
619  종로12        57176
620  종로13        20900
621  중랑01         9908
622  중랑02       126615

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2010
0    0017       141084
1     01A        16823
2     01B        16209
3      02        85566
4      03         3707
..    ...          ...
618  종로11        71223
619  종로12        57687
620  종로13        23192
621  중랑01        10665
622  중랑02       143897

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2011
0    0017       144431
1     01A        16606
2     01B        15628
3      02        60524
4      03         2986
..    ...          ...
618  종로11        71792
619  종로12        61499
620  종로13        24991
621  중랑01        10845
622  중랑02       148630

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2012
0    0017       122226
1     01A        13747
2     01B        13743
3      02        40888
4      03         1521
..    ...          ...
618  종로11        45656
619  종로12        56413
620  종로13        16227
621  중랑01         8781
622  중랑02       120946

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2101
0    0017       121519
1     01A        13933
2     01B        13591
3      02        34271
4      03         1459
..    ...          ...
618  종로11        46535
619  종로12        55128
620  종로13        13493
621  중랑01         8521
622  중랑02       118797

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2102
0    0017       121445
1     01A        14227
2     01B        13115
3      02        44841
4      03         2163
..    ...          ...
617  종로11        52212
618  종로12        54726
619  종로13        14439
620  중랑01         8316
621  중랑02       111067

[622 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2103
0    0017       148810
1     01A        18792
2     01B        17955
3      02        49037
4      03         3453
..    ...          ...
621  종로11        64348
622  종로12        63193
623  종로13        24497
624  중랑01         9837
625  중랑02       143969

[626 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2104
0    0017       143706
1     01A        19199
2     01B        18240
3      02        77423
4      03         3687
..    ...          ...
615  종로11        67550
616  종로12        63816
617  종로13        22935
618  중랑01         9233
619  중랑02       146184

[620 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2105
0    0017       143427
1     01A        19654
2     01B        17970
3      02        71493
4      03         4486
..    ...          ...
615  종로11        71505
616  종로12        61860
617  종로13        22438
618  중랑01         9158
619  중랑02       136623

[620 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2106
0    0017       152086
1     01A        22135
2     01B        20859
3      02        62910
4      03         4713
..    ...          ...
614  종로11        71206
615  종로12        68540
616  종로13        24336
617  중랑01         9565
618  중랑02       146614

[619 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2107
0    0017       147215
1     01A        20889
2     01B        20546
3      02        46208
4      03            7
..    ...          ...
615  종로11        62333
616  종로12        65914
617  종로13        20158
618  중랑01         9051
619  중랑02       135158

[620 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2108
0    0017       140569
1     01A        20742
2     01B        19467
3      02        61200
4      04        35628
..    ...          ...
615  종로11        63334
616  종로12        62355
617  종로13        19773
618  중랑01         7987
619  중랑02       129240

[620 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2109
0    0017       138070
1     01A        18830
2     01B        17996
3      02        83738
4      04        50887
..    ...          ...
615  종로11        66762
616  종로12        56873
617  종로13        22499
618  중랑01         6896
619  중랑02       126732

[620 rows x 2 columns]

['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2110
0    0017       145538
1     01A        18929
2     01B        18243
3      02       109683
4      04        56614
..    ...          ...
615  종로11        74825
616  종로12        57061
617  종로13        22666
618  중랑01         6669
619  중랑02       143171

[620 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2111
0    0017       152048
1     01A        21194
2     01B        19753
3      02        83882
4      04        48163
..    ...          ...
619  종로11        80628
620  종로12        60717
621  종로13        23510
622  중랑01         6909
623  중랑02       155116

[624 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2112
0    0017       152302
1     01A        20427
2     01B        19009
3      02        59580
4      04        36291
..    ...          ...
620  종로11        72552
621  종로12        57149
622  종로13        21184
623  중랑01         6516
624  중랑02       151704

[625 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2201
0    0017       137052
1     01A        19015
2     01B        17938
3      02        65241
4      04        38427
..    ...          ...
619  종로11        70964
620  종로12        53453
621  종로13        16151
622  중랑01         6030
623  중랑02       126998

[624 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2202
0    0017       118676
1     01A        15593
2     01B        15119
3      02        52641
4      04        31211
..    ...          ...
616  종로11        60453
617  종로12        47850
618  종로13        13645
619  중랑01         5061
620  중랑02       108771

[621 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2203
0    0017       132785
1     01A        18599
2     01B        18241
3      02        55983
4      04        33828
..    ...          ...
616  종로11        69073
617  종로12        53669
618  종로13        23877
619  중랑01         5714
620  중랑02       145655

[621 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
     노선번호  승하차_평균_2204
0    0017       143296
1     01A        22188
2     01B        20805
3      02       115785
4      04        61659
..    ...          ...
620  종로11        97758
621  종로12        61111
622  종로13        28826
623  중랑01         6179
624  중랑02       155219

[625 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2205
0    0017       158312
1      01       141294
2     01A        25635
3     01B        22497
4      02         4693
..    ...          ...
623  종로11       124118
624  종로12        69117
625  종로13        33483
626  중랑01         6912
627  중랑02       166319

[628 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2206
0    0017       156412
1      01       163470
2     01A        20960
3     01B        18956
4    0411        25537
..    ...          ...
624  종로11       110137
625  종로12        68175
626  종로13        29916
627  중랑01         6776
628  중랑02       149313

[629 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2207
0    0017       169743
1      01       150430
2    0411       207942
3     100       487955
4     101       476709
..    ...          ...
618  종로11       101393
619  종로12        74711
620  종로13        22804
621  중랑01         5890
622  중랑02       144063

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2208
0    0017       163858
1      01       172416
2    0411       203795
3     100       460149
4     101       461332
..    ...          ...
618  종로11       102391
619  종로12        74050
620  종로13        22057
621  중랑01         4685
622  중랑02       142612

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2209
0    0017       158779
1      01       189031
2    0411       232102
3     100       482851
4     101       464849
..    ...          ...
618  종로11       101735
619  종로12        69428
620  종로13        33112
621  중랑01         4286
622  중랑02       162212

[623 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2210
0    0017       160846
1      01       229537
2    0411       246353
3     100       500161
4     101       482650
..    ...          ...
620  종로11       108683
621  종로12        68448
622  종로13        32503
623  중랑01         4306
624  중랑02       163772

[625 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2211
0    0017       157913
1      01       190698
2    0411       252013
3     100       492782
4     101       480451
..    ...          ...
617  종로11        95991
618  종로12        73526
619  종로13        33725
620  중랑01         4072
621  중랑02       165688

[622 rows x 2 columns]
['사용일자', '노선번호', '노선명', '버스정류장ARS번호', '역명', '승차총승객수', '하차총승객수', '등록일자']
1
     노선번호  승하차_평균_2212
0    0017       166239
1      01       169771
2    0411       252222
3     100       496575
4     101       500656
..    ...          ...
623  종로11        95364
624  종로12        72249
625  종로13        28634
626  중랑01         4107
627  중랑02       158655

[628 rows x 2 columns]

,승하차_평균_1501,승하차_평균_1502,승하차_평균_1503,승하차_평균_1504,승하차_평균_1505,승하차_평균_1506,승하차_평균_1507,승하차_평균_1508,승하차_평균_1509,승하차_평균_1510,...,승하차_평균_2203,승하차_평균_2204,승하차_평균_2205,승하차_평균_2206,승하차_평균_2207,승하차_평균_2208,승하차_평균_2209,승하차_평균_2210,승하차_평균_2211,승하차_평균_2212
노선번호,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,141294,163470,150430,172416,189031,229537,190698,169771
2,89065,81164,91316,125745,135108,73445,73054,85973,81681,84729,...,55983,115785,4693,0,0,0,0,0,0,0
3,40176,33309,35269,44765,49275,26210,30762,46422,44784,42152,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,33828,61659,2150,0,0,0,0,0,0,0
5,50488,48445,45704,57310,60338,31233,36686,59144,66140,69513,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
종로11,104105,91142,105571,107068,114475,90830,105741,111103,101171,105088,...,69073,97758,124118,110137,101393,102391,101735,108683,95991,95364
종로12,81691,67073,83137,81627,74401,61782,79382,79812,74815,76601,...,53669,61111,69117,68175,74711,74050,69428,68448,73526,72249
종로13,32757,29184,58565,58687,57586,55115,43325,40204,57340,59359,...,23877,28826,33483,29916,22804,22057,33112,32503,33725,28634
중랑01,17239,15302,18798,18460,18248,17177,17108,16123,16923,17350,...,5714,6179,6912,6776,5890,4685,4286,4306,4072,4107
중랑02,199103,174694,254811,244027,230591,211303,193553,188940,212767,225801,...,145655,155219,166319,149313,144063,142612,162212,163772,165688,158655

In [65]:
df_bus.to_csv('df_bus.csv', encoding = 'utf-8-sig')