In [1]:
import os
import pandas as pd
import numpy as np
PATH = '지하철호선별_역별_승하차_인원/'
file_list, csv_list = os.listdir(PATH), list()
for file in file_list:
    if file.split('.')[-1] == 'csv':
        csv_list.append(file)
boolean_flag = True
for csv_file in csv_list:
    try:
        df_whole = pd.read_csv(PATH+csv_file, encoding = 'cp949')
    except:
        df_whole = pd.read_csv(PATH+csv_file, encoding = 'utf-8-sig')
    if str(df_whole.iloc[0,-1]) == 'nan':
        column_list = df_whole.columns
        df_whole = df_whole.reset_index()
        df_whole.columns = ['사용일자', '노선명', '역명', '승차총승객수', '하차총승객수', '등록일자','NaN']
        df_whole = df_whole.dropna(axis = 1)
    df_whole = df_whole.groupby(['역명']).mean()[['승차총승객수','하차총승객수']]
    df_whole['승하차_평균_{}'.format(csv_file.split('.')[-2][-4:])] = (df_whole['승차총승객수'] + df_whole['하차총승객수']) / 2
    df_whole = df_whole[['승하차_평균_{}'.format(csv_file.split('.')[-2][-4:])]].astype('int')
    df_whole = df_whole.reset_index()
    if boolean_flag:
        df_subway = df_whole
        boolean_flag = False
    else:
        df_subway = pd.merge(df_subway, df_whole, on = '역명', how = 'outer')
list_name = list(df_subway['역명'])
list_subway = list()
for name in list_name:
    name = name.split('(')[0]
    list_subway.append(name)
df_subway['역명'] = list_subway
df_subway = df_subway.groupby('역명').sum()
df_subway = df_subway.astype('int')
df_subway

,승하차_평균_1501,승하차_평균_1502,승하차_평균_1503,승하차_평균_1504,승하차_평균_1505,승하차_평균_1506,승하차_평균_1507,승하차_평균_1508,승하차_평균_1509,승하차_평균_1510,...,승하차_평균_2202,승하차_평균_2203,승하차_평균_2204,승하차_평균_2205,승하차_평균_2206,승하차_평균_2207,승하차_평균_2208,승하차_평균_2209,승하차_평균_2210,승하차_평균_2211
역명,,,,,,,,,,,,,,,,,,,,,
4.19민주묘지,0,0,0,0,0,0,0,0,0,0,...,2208,2785,3202,3407,2935,2593,2499,3660,3597,3813
가능,7295,7136,8221,8438,8137,7599,7594,7284,7877,8106,...,5012,5450,6249,6561,6340,6129,5857,6368,6440,6487
가락시장,7837,7445,8161,8230,7683,7238,7576,7045,7572,7770,...,6301,6518,7505,7784,7697,7463,7276,7654,7824,8275
가산디지털단지,29487,27781,30906,31466,27662,29051,29753,26351,28149,29704,...,22568,23028,25959,26556,26401,26126,25317,25958,25727,28371
가양,18585,18088,20655,21289,20178,19123,19735,18627,19411,20320,...,15383,15715,18124,19218,19063,18938,18371,19174,19720,20663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
회기,27442,26635,34240,34307,32788,28497,27326,26436,30677,31920,...,18601,20174,23237,25101,23524,22321,21724,26385,26263,27710
회룡,13477,12790,14586,14793,14426,13024,13370,12852,13633,14354,...,9730,10141,11789,12479,12101,11591,11112,11964,12302,12369
회현,29346,27269,31914,33411,32281,27011,29182,27157,28720,31636,...,17319,18558,22227,24119,23264,22342,20733,22278,24489,25310
효창공원앞,7526,7039,8813,8933,8229,7786,7500,6750,7774,8261,...,3697,3913,4487,4776,4605,4382,4296,4814,4982,5111
흑석,10258,9616,13449,13576,12893,10834,9690,9095,11499,11646,...,6201,7199,8008,8653,8077,7517,7230,9274,8904,9709

In [3]:
df_subway.to_csv('df_subway.csv',sep = ',', encoding = 'utf-8-sig')